### ISSUE TITLE
Middlewares?

### ISSUE THREAD

**Issue by JelF** [umbrellio/polist#1]
I.e. i wannt to write
```
def call
  ActiveRecord::Base.transaction do
    ...
  end
end
```

Now the best idea is to write (imo)
```
def call
  ActiveRecord::Base.transaction { call_in_transaction }
end
```

Maybe we can build some middleware api, i.e.

```
around_call { |block| ActiveRecord::Base.transaction(&block) }
```

The easiest way is to include ActiveSupport::Callbacks and make aliases on self-method. This support could be added in separate concern, like Polist::Callbacks. The only downside is AS dependency, which is shitty

**Comment by JelF** [comment]
I can make a PR if this API seems good

**Comment by tycooon** [comment]
Personally I don’t like callbacks and try to always avoid them, and I also wanted to keep API as simple as possible, so that people are free to subclass the `Polist::Service` and implement the logic there. If you don’t like this approach, you are free to implement some kind of plugin system (like in Sequel) and make it a plugin, because I don’t want this functionality to be in every service class.

**Comment by JelF** [comment]
@tycooon ok, ill make a PR in week
